config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, controllers: { registrations: "users/registrations" }
  devise_for :users
  # devise_for :admins
  devise_for :admins, controllers: { registrations: 'admins/registrations' }

  root 'pages#index'

  resources :products
  resources :users
  # devise_for :users
  # devise_for :admins
  resources :companies
  resources :admin_dashboards
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_admin_dashboard.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Super Admin Dashbaord</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'vendors', companies_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'users', users_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign out', destroy_admin_session_path, method: :delete, class: 'nav-link' if current_admin %>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Logged in Admin: <%= current_admin.email %></a>
      </li>
    </ul>
  </div>
</nav>

<%= yield %>

app/views/partials/_user_dashboard.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Hurapos Customer Dashbaord (<%= current_user.company.name %> company)</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Our Products', products_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'employees', users_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' if current_user %>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Logged in User: <%= current_user.email %>( <%= current_user.role %> )</a>
      </li>
    </ul>
  </div>
</nav>

<%= yield %>